<script setup>
import { RouterLink } from 'vue-router'
import logoSvg from '../assets/logo.svg'

const lastUpdated = 'February 12, 2026'
</script>

<template>
<div class="min-h-screen bg-godot-dark text-godot-text">
    <!-- Header -->
    <header class="border-b border-godot-border bg-godot-darker/50 backdrop-blur-xl">
        <div class="max-w-7xl mx-auto px-6 h-16 flex items-center justify-between">
            <router-link to="/" class="flex items-center gap-3">
                <img :src="logoSvg" alt="Godoty Logo" class="w-8 h-8" />
                <span class="font-bold text-xl tracking-tight text-white">Godoty</span>
            </router-link>
        </div>
    </header>
    
    <!-- Content -->
    <main class="max-w-4xl mx-auto px-6 py-16">
        <div class="mb-12">
            <h1 class="text-4xl font-bold text-white mb-4">Terms of Service</h1>
            <p class="text-godot-muted">Last updated: {{ lastUpdated }}</p>
        </div>
        
        <div class="prose prose-invert max-w-none space-y-8">
            <!-- Introduction -->
            <section>
                <h2 class="text-2xl font-bold text-white mb-4">1. Introduction</h2>
                <p class="text-godot-muted leading-relaxed">
                    Welcome to Godoty ("we," "our," or "us"). These Terms of Service ("Terms") govern your access to and 
                    use of the Godoty desktop application, website at godoty.app, and related services (collectively, the "Service"). 
                    By using the Service, you agree to be bound by these Terms.
                </p>
                <p class="text-godot-muted leading-relaxed mt-4">
                    Godoty is an AI-integrated desktop application designed to bridge the gap between AI assistants and the Godot Engine.
                </p>
            </section>
            
            <!-- Eligibility -->
            <section>
                <h2 class="text-2xl font-bold text-white mb-4">2. Eligibility</h2>
                <p class="text-godot-muted leading-relaxed">
                    You must be at least 13 years old to use the Service. By using Godoty, you represent that you meet these requirements.
                </p>
            </section>
            
            <!-- Acceptable Use -->
            <section>
                <h2 class="text-2xl font-bold text-white mb-4">3. Acceptable Use</h2>
                <p class="text-godot-muted leading-relaxed">
                    You agree not to use the Service to:
                </p>
                <ul class="list-disc pl-6 mt-4 text-godot-muted space-y-2">
                    <li>Violate any applicable laws or regulations</li>
                    <li>Generate malicious code, malware, or content intended to harm others</li>
                    <li>Infringe upon intellectual property rights of third parties</li>
                    <li>Attempt to reverse engineer, decompile, or exploit the Service</li>
                </ul>
            </section>
            
            <!-- Intellectual Property -->
            <section>
                <h2 class="text-2xl font-bold text-white mb-4">4. Intellectual Property</h2>
                <p class="text-godot-muted leading-relaxed">
                    <strong class="text-white">Your Content:</strong> You retain ownership of any code, projects, or content 
                    you provide to the Service.
                </p>
                <p class="text-godot-muted leading-relaxed mt-4">
                    <strong class="text-white">AI-Generated Content:</strong> Code and suggestions generated by Godoty are 
                    provided for your use. You are responsible for reviewing and testing any AI-generated code.
                </p>
                <p class="text-godot-muted leading-relaxed mt-4">
                    <strong class="text-white">Our Property:</strong> The Godoty name, logo, software, and all related 
                    intellectual property remain our exclusive property.
                </p>
            </section>
            
            <!-- Disclaimer of Warranties -->
            <section>
                <h2 class="text-2xl font-bold text-white mb-4">5. Disclaimer of Warranties</h2>
                <p class="text-godot-muted leading-relaxed">
                    THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND. 
                    AI-generated content may contain errors and should always be reviewed before use.
                </p>
            </section>
            
            <!-- Limitation of Liability -->
            <section>
                <h2 class="text-2xl font-bold text-white mb-4">6. Limitation of Liability</h2>
                <p class="text-godot-muted leading-relaxed">
                    TO THE MAXIMUM EXTENT PERMITTED BY LAW, WE SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, 
                    OR CONSEQUENTIAL DAMAGES ARISING FROM YOUR USE OF THE SERVICE.
                </p>
            </section>
            
            <!-- Governing Law -->
            <section>
                <h2 class="text-2xl font-bold text-white mb-4">7. Governing Law</h2>
                <p class="text-godot-muted leading-relaxed">
                    These Terms shall be governed by and construed in accordance with the laws of the 
                    United States.
                </p>
            </section>
            
            <!-- Contact -->
            <section>
                <h2 class="text-2xl font-bold text-white mb-4">8. Contact Us</h2>
                <p class="text-godot-muted leading-relaxed">
                    If you have any questions about these Terms, please contact us at:
                </p>
                <p class="text-godot-blue mt-4">support@goodfaithgames.com</p>
            </section>
        </div>
        
        <!-- Back Link -->
        <div class="mt-16 pt-8 border-t border-godot-border">
            <router-link to="/" class="text-godot-muted hover:text-godot-blue transition-colors inline-flex items-center gap-2">
                <i class="ph ph-arrow-left"></i>
                Back to Home
            </router-link>
        </div>
    </main>
</div>
</template>
